apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    hostaliases-injector: enabled
---              
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: application
  name: webhook-dp-test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: sleep
        image: ubuntu
        args: ["sleep", "36500000"]

---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    hostaliases-injector: enabled
---              
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: application
  name: webhook-job-test
  namespace: test
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sleep
        image: ubuntu
        args: ["sleep", "36500000"]

